version: "3.8"
services:
  app:
    container_name: "fastapi_pytest_app"
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
      - waitfordb
    env_file:
      - docker/.env
    command: ["alembic", "upgrade", "head", "&&", "pytest", "-s"]
    volumes:
      - .:/workspace/fastapi-sqlalchemy-alembic-pytest-sample
    working_dir: /workspace/fastapi-sqlalchemy-alembic-pytest-sample
  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432
  db:
    image: "postgres:13.1-alpine"
    container_name: "fastapi_pytest_db"
    env_file:
      - docker/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
      TZ: UTC
    ports:
      - "5432:5432"